---
title: "Wind Potential"
author: "Sam Campbell & John Rooney"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Install packages, message=FALSE, warning=FALSE}
#Import the tidyverse library 
library(tidyverse)
library(lubridate)

#install.packages('sf')
library(sf)
#install.packages('leaflet')
library(leaflet)
#install.packages('mapview')
library(mapview); mapviewOptions(fgb = FALSE)
library(RColorBrewer)

#Disable on-the-fly projections
sf::sf_use_s2(FALSE)

```

```{r read in counties}
wy_counties <- st_read("./Data/Spatial/cb_2021_us_county_20m/cb_2021_us_county_20m.shp") %>% 
  filter(STATEFP == 56) #filter for WY
```

```{r read and wrangle svi data}

#read in svi data for WY
svi2020_wy_raw <- read.csv("./Data/Raw/Wyoming_COUNTY.csv", 
  colClasses = c('FIPS' = 'factor'))

#check raw structure
str(svi2020_wy_raw)

#select needed columns
svi2020_wy_processed <- svi2020_wy_raw %>%
  select(COUNTY, FIPS, LOCATION, E_TOTPOP, E_POV150, E_MINRTY)

#save processed file
write.csv(svi2020_wy_processed, row.names = F, file = "./Data/Processed/svi2020_wy_processed.csv")

#Check structure
str(svi2020_wy_processed)

```

```{r join svi to county data}

#join svi to county data
counties_sf_join <- wy_counties %>% 
  left_join(svi2020_wy_processed, by = c("GEOID" = "FIPS") )

#View with mapview
mapview(counties_sf_join, 
        zcol = 'E_POV150')#, 
        #col.regions = brewer.pal(2, 'RdBu')) #+ 
 # mapview(epa_pm25_sites_sf, cex = 'maxPM')

#view with ggplot
#ggplot() + 
  #geom_sf(data=counties_sf_join,aes(fill = E_POV),alpha=0.3) + 
  #scale_fill_gradient2(low="red",high="blue",midpoint = 60000) + 
  #geom_sf(data=epa_pm25_sites_sf)

#Calculate percentage poverty by county with a new column
counties_sf_join <- 
  counties_sf_join %>% 
  mutate(PercentPov = ((E_POV150 / E_TOTPOP)*100))

#View percentage poverty by county with mapview
mapview(counties_sf_join, 
        zcol = 'PercentPov')

```

```{r powerplants in WY}
powerplants_sf <- st_read('https://opendata.arcgis.com/datasets/ee0263bd105d41599be22d46107341c3_0.geojson')

#Reveal the field names
colnames(powerplants_sf)

#How many records
nrow(powerplants_sf)

#View on a map - specify the geometry column to draw faster
plot(powerplants_sf$geometry)

#Filter for just powerplants found in NC
wy_powerplants_sf <- powerplants_sf %>% 
  filter(STATE == "WY") 

#Have a look the variety of types (and number of each)
wy_powerplants_sf %>% 
  st_drop_geometry() %>% 
  count(TYPE, sort=TRUE)

# Examine counts by prim fuel type
ggplot(wy_powerplants_sf) + 
  geom_sf(aes(color = PRIM_FUEL)) 

#counts by type
ggplot(wy_powerplants_sf) + 
  geom_sf(aes(color = TYPE)) 

#map counties, svi, powerplants
mapview(counties_sf_join, 
        zcol = 'E_POV150') +
  mapview(wy_powerplants_sf,
          zcol = 'TYPE')

#aggregate power plants by energy type for simpler visualization
wy_powerplants_sf <- 
  wy_powerplants_sf %>% 
  mutate(FossilFuel = c(TYPE = "CONVENTIONAL STEAM COAL", 
                        "NATURAL GAS FIRED COMBUSTION TURBINE", 
                        "ALL OTHER; NATURAL GAS FIRED COMBUSTION TURBINE", 
                        "PETROLEUM LIQUIDS", 
                        "CONVENTIONAL STEAM COAL; NATURAL GAS FIRED COMBUSTION TURBINE", 
                        "NATURAL GAS INTERNAL COMBUSTION ENGINE; NATURAL GAS STEAM TURBINE; OTHER GASES; PETROLEUM LIQUIDS", 
                        "NATURAL GAS FIRED COMBINED CYCLE; NATURAL GAS FIRED COMBUSTION TURBINE", 
                        "NATURAL GAS STEAM TURBINE")) %>% 
  mutate(Renewable = c(TYPE = "CONVENTIONAL HYDROELECTRIC", 
                        "ONSHORE WIND TURBINE")) %>% 
  mutate(Unknown = c(TYPE = "ALL OTHER",
                      "NOT AVAILABLE",
                     "OTHER GASES"))
```

```{r read in HUC12 dataset}
#read in HUC12 dataset
HUC12 <- st_read("./Data/Spatial/HUC12_Watershed_Boundaries/NHD_-_Watershed_Boundaries_HUC_12.shp")

#view HUC12 data with mapview
mapview(HUC12)

```

```{r compute centroids of HUC12s}
#apply st_centroid function to geometry column of HUC12 dataset
HUC12Centroids <- HUC12 %>% 
  mutate(geometry = st_centroid(geometry))

#check that the HUC12 centroids show up as expected when mapped
mapview(HUC12Centroids)

#check the crs of each dataframe
st_crs(wy_counties)
#^uses NAD83
st_crs(HUC12Centroids)
#^uses WGS 84

#transform the crs for HUC12Centroids dataframe to match wy_counties dataframe
#EPSG code for NAD83 is 4269
HUC12CentroidsNAD83 <- 
  st_transform(HUC12Centroids,4269)

#check crs for transformed HUC12CentroidsNAD83 dataframe
st_crs(HUC12CentroidsNAD83)
#now uses NAD83, same as wy_counties dataframe

#Tag each centroid with the county in which it falls using st_join function
HUC12Counties <- 
  st_join(wy_counties, HUC12CentroidsNAD83) 

#map newly created dataframe of HUC12Counties
mapview(HUC12Counties)
```

```{r plotting wind data by HUC12s and counties}
#Read in HUC12 wind energy data
wind_raw <- read.csv('https://raw.githubusercontent.com/ENV859/EnviroAtlasData/main/Wind_Energy.csv',
  colClasses = c('HUC_12' = 'factor'))

#Join wind_raw dataframe with HUC12Counties dataframe to filter the wind data for Wyoming counties
HUC12CountiesWind <- HUC12Counties %>% 
  left_join(wind_raw, by = c("HUC12" = "HUC_12"))

#Create tidied dataframe of wind energy by county and HUC12
TidyHUC12CountiesWind <- HUC12CountiesWind %>% 
  select(NAME, NAMELSAD, STATE_NAME, HUC12, AvgWindEnergy, kWhkm2day, geometry)

#view new tidied data as a scatterplot
PlotWindByCounty <- 
  ggplot(TidyHUC12CountiesWind,
       aes(x = NAME,
           y = AvgWindEnergy)) +
  geom_boxplot() +
  labs(x = "County Name", y = "Avg Wind Speed in GWh / km^2 / day",
       title = "Wind Speeds by County in Wyoming") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
print(PlotWindByCounty)
```

```{r alternative approach to plotting wind data, with averages at the county level}
#Creating new data frame, calculating average wind energy by county
AvgWindByCounty <- 
  TidyHUC12CountiesWind %>% 
  drop_na(AvgWindEnergy) %>% 
  group_by(NAME) %>% 
  summarize(AvgWind = mean(AvgWindEnergy))
#^currently generates warning message "although coordinates are longitude/latitude, st_union assumes that they are planar"

#View new AvgWindByCounty data as a scatterplot
PlotAvgWindByCounty <- 
  ggplot(AvgWindByCounty,
       aes(x = NAME,
           y = AvgWind)) +
  geom_point() +
  labs(x = "County Name", y = "Avg Wind Speed in GWh / km^2 / day",
       title = "Average Wind Speed by County in Wyoming") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
print(PlotAvgWindByCounty)
```

```{r example from lesson 9 on computing and mapping wind energy data}
#Example for how to compute HUC8 wind energy
wind_raw <- read.csv('https://raw.githubusercontent.com/ENV859/EnviroAtlasData/main/Wind_Energy.csv',
  colClasses = c('HUC_12' = 'factor')) %>%  
  #mutate(HUC_8 = substr(HUC_12,1,8)) %>% 
  #group_by(HUC_8) %>% 
  #summarize(SumWindEnergy = sum(AvgWindEnergy))
  
#Join to HUC_8 features
huc8_sf_join = merge(x = huc8_sf,
                     y = wind_raw,
                     by.x = 'HUC_8',
                     by.y = 'HUC_8')

#View the outputs
ggplot(data=huc8_sf_join) +
  geom_sf(aes(fill=SumWindEnergy)) +
  labs(
    title='Wind energy by HUC 8',
    fill ='MW/year'
  )
```


