---
output: 
  html_document:
    keep_tex: yes
    fig_caption: yes
    number_sections: yes
geometry: margin=2.54cm
title: "Exploring Social Vulnerability, Power Plant Siting, and Wind Energy Potential in Wyoming"
subtitle: "https://github.com/jkrooney/Campbell_Rooney_ENV872_EDASp23_FinalProject"
author: "Sam Campbell & John Rooney"
fontsize: 12pt
mainfont: Times New Roman

---

\newpage
\tableofcontents 
\newpage
\listoftables 
\newpage
\listoffigures 
\newpage

```{r setup, include=FALSE}
# Set your working directory
setwd()

# Load your packages
library(tidyverse)
library(lubridate)
library(sf)
library(leaflet)
library(mapview); mapviewOptions(fgb = FALSE)
library(RColorBrewer)

#Disable on-the-fly projections
sf::sf_use_s2(FALSE)

# Set your ggplot theme

# Load your datasets

```


# Rationale and Research Questions
The Inflation Reduction Act (IRA) was passed by Congress in late summer of 2022. The IRA is a generational piece of legislation providing funding and incentives for domestic energy production in the United States, offering the strongest government support yet for transitioning to renewable energy and confronting the challenges posed by climate change.

Among the many programs included in the IRA is one offering funding to help traditional fossil fuel communities transition to renewable energy production. To help us answer these questions, we decided to look at the state of Wyoming as a case study. Wyoming was selected for two main reasons. First, it is a state heavily reliant on traditional fossil fuel extraction and production. Second, we knew that Wyoming has relatively abundant wind energy potential, and that data existed that would help us understand and quantify wind energy potential throughout the state. 

This led us to two research questions:
1) What relationship is there between socially vulnerable communities and the presence of power plants?   
2) What potential is there for renewable energy production in communities considered socially vulnerable? 


\newpage

# Dataset Information



\newpage

# Exploratory Analysis 



\newpage

# Analysis



## Question 1: <insert specific question here and add additional subsections for additional questions below, if needed>

## Question 2: 




\newpage

# Summary and Conclusions


\newpage

# References
<add references here if relevant, otherwise delete this section> 
